repository:
 
  # The name of the repository. Changing this will rename the repository
  name: pre-check
 
  # A short description of the repository that will show up on GitHub
  description: Implementation Services project pre-check toolkits 
 
  # A URL with more information about the repository
  homepage: https://www.beyondtrust.com/
 
  # A comma-separated list of topics to set on the repository
  topics: bash, vbscript
 
  # Either `true` to make the repository private, or `false` to make it public.
  private: false
